---
title: "Tufte Handout"
subtitle: "An implementation in R Markdown"
author: "JJ Allaire and Yihui Xie"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: bibtex
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: bibtex
    latex_engine: xelatex
bibliography: bibliography.bib
link-citations: yes
---

```{r setup, include = FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)

  knitr::opts_chunk$set(
    collapse = TRUE,
    message = FALSE,
    comment = "#>"
  )
  knitr::read_chunk("r-code.R")
  
  # Set up knitr caching
  knitr::opts_chunk$set(autodep = TRUE,
                        cache.comments = FALSE,
                        cache.extra = list(R.version, sessionInfo()))
  knitr::dep_auto()
                        
```

```{r calculation, eval = TRUE}

```

First, we read in the starwars data, then output a figure:
```{r, starwars-plot}
library(tidyverse)
starwars %>% filter(species == "Human") %>% 
  ggplot() +
  aes(x=height, y = mass) + geom_point()
```

Now we output a table which is cached:
```{r starwars-tbl, cache=TRUE}
starwars %>%
  filter(species == "Human") %>%
  select(name, height, mass, homeworld) 

```


Here is an in-text citation using bibtex: [@DBLP:journals/corr/abs-1802-03311]. Here is another: [@Goodman341ps12].


# References cited

